"""
Export Service for Generator Tugas Random SPSS & Excel
Author: BieM363 (https://github.com/BieM363)
Exports datasets to formatted Excel (.xlsx), CSV (.csv), and IBM SPSS Syntax (.sps).
"""

import io
from typing import Any, Dict, List
import pandas as pd
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter


class ExportService:
    @staticmethod
    def export_to_excel(df: pd.DataFrame, meta: Dict[str, Any]) -> io.BytesIO:
        output = io.BytesIO()
        with pd.ExcelWriter(output, engine="openpyxl") as writer:
            # 1. Dataset Sheet
            df.to_excel(writer, sheet_name="Data_Responden", index=False)

            # 2. Data Dictionary Sheet
            dictionary = meta.get("dictionary", {})
            dict_df = pd.DataFrame([
                {"Nama_Variabel": k, "Tipe_Data": "Numerik" if pd.api.types.is_numeric_dtype(df[k]) else "Kategorik/String", "Keterangan_Definisi": v}
                for k, v in dictionary.items() if k in df.columns
            ])
            dict_df.to_excel(writer, sheet_name="Kamus_Variabel", index=False)

            # 3. Excel Formula Hints Sheet
            hints_data = [
                {"Analisis": "Rata-rata (Mean)", "Formula Excel": "=AVERAGE(range)", "Contoh": "=AVERAGE(E2:E61)"},
                {"Analisis": "Nilai Tengah (Median)", "Formula Excel": "=MEDIAN(range)", "Contoh": "=MEDIAN(E2:E61)"},
                {"Analisis": "Modus", "Formula Excel": "=MODE.SNGL(range)", "Contoh": "=MODE.SNGL(E2:E61)"},
                {"Analisis": "Standar Deviasi Sampel", "Formula Excel": "=STDEV.S(range)", "Contoh": "=STDEV.S(E2:E61)"},
                {"Analisis": "Varians Sampel", "Formula Excel": "=VAR.S(range)", "Contoh": "=VAR.S(E2:E61)"},
                {"Analisis": "Kuartil 1 (Q1)", "Formula Excel": "=QUARTILE.INC(range, 1)", "Contoh": "=QUARTILE.INC(E2:E61, 1)"},
                {"Analisis": "Kuartil 3 (Q3)", "Formula Excel": "=QUARTILE.INC(range, 3)", "Contoh": "=QUARTILE.INC(E2:E61, 3)"},
                {"Analisis": "Korelasi Pearson", "Formula Excel": "=CORREL(array1, array2)", "Contoh": "=CORREL(E2:E61, H2:H61)"},
                {"Analisis": "Slope Regresi Linear", "Formula Excel": "=SLOPE(known_y's, known_x's)", "Contoh": "=SLOPE(H2:H61, E2:E61)"},
                {"Analisis": "Intercept Regresi Linear", "Formula Excel": "=INTERCEPT(known_y's, known_x's)", "Contoh": "=INTERCEPT(H2:H61, E2:E61)"},
                {"Analisis": "Koefisien R-Square (R²)", "Formula Excel": "=RSQ(known_y's, known_x's)", "Contoh": "=RSQ(H2:H61, E2:E61)"},
                {"Analisis": "Uji t Dua Sampel", "Formula Excel": "=T.TEST(array1, array2, 2, 2)", "Contoh": "=T.TEST(A2:A30, B2:B30, 2, 2)"},
            ]
            pd.DataFrame(hints_data).to_excel(writer, sheet_name="Panduan_Rumus_Excel", index=False)

            # Styling Workbook
            wb = writer.book
            wb.properties.creator = "BieM363"
            wb.properties.lastModifiedBy = "BieM363"
            wb.properties.title = f"StatTask AutoGen - {meta.get('theme_name', 'Dataset Statistik')}"
            wb.properties.description = "Generated by StatTask AutoGen by BieM363 (https://github.com/BieM363)"

            header_fill = PatternFill(start_color="1E3A8A", end_color="1E3A8A", fill_type="solid")
            header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
            thin_border = Border(
                left=Side(style="thin", color="E5E7EB"),
                right=Side(style="thin", color="E5E7EB"),
                top=Side(style="thin", color="E5E7EB"),
                bottom=Side(style="thin", color="E5E7EB"),
            )

            for ws in wb.worksheets:
                # Format headers
                for cell in ws[1]:
                    cell.fill = header_fill
                    cell.font = header_font
                    cell.alignment = Alignment(horizontal="center", vertical="center")

                # Auto-fit column widths
                for col in ws.columns:
                    max_len = 0
                    col_letter = get_column_letter(col[0].column)
                    for cell in col:
                        cell.border = thin_border
                        val_str = str(cell.value or "")
                        max_len = max(max_len, len(val_str))
                    ws.column_dimensions[col_letter].width = min(max(max_len + 4, 12), 45)

        output.seek(0)
        return output

    @staticmethod
    def export_to_csv(df: pd.DataFrame) -> str:
        return df.to_csv(index=False)

    @staticmethod
    def export_to_spss_syntax(df: pd.DataFrame, meta: Dict[str, Any], filename_hint: str = "dataset.csv") -> str:
        """
        Generates IBM SPSS Syntax (.sps) file for quick data loading & analysis.
        """
        cols = list(df.columns)
        theme_name = meta.get("theme_name", "Dataset Statistik")

        lines = [
            f"* ===================================================================.",
            f"* IBM SPSS SYNTAX: {theme_name.upper()}.",
            f"* Created & Developed by BieM363 (https://github.com/BieM363).",
            f"* Generated by StatTask AutoGen.",
            f"* ===================================================================.",
            f"",
            f"* 1. Perintah Import CSV ke SPSS.",
            f"GET DATA  /TYPE=TXT",
            f"  /FILE='{filename_hint}'",
            f"  /DELCASE=LINE",
            f"  /DELIMITERS=\",\"",
            f"  /QUALIFIER='\"'",
            f"  /ARRANGEMENT=DELIMITED",
            f"  /FIRSTCASE=2",
            f"  /IMPORTCASE=ALL",
            f"  /VARIABLES=",
        ]

        for col in cols:
            if pd.api.types.is_numeric_dtype(df[col]):
                lines.append(f"    {col} F8.2")
            else:
                lines.append(f"    {col} A50")
        lines.append("  .")
        lines.append("CACHE.")
        lines.append("EXECUTE.")
        lines.append("")

        # Variable labels
        lines.append("* 2. Pelabelan Variabel (Variable Labels).")
        lines.append("VARIABLE LABELS")
        for col, desc in meta.get("dictionary", {}).items():
            if col in cols:
                lines.append(f"  {col} '{desc}'")
        lines.append("  .")
        lines.append("EXECUTE.")
        lines.append("")

        # Sample Analysis syntax templates
        lines.append("* 3. Template Analisis Deskriptif.")
        num_cols = [c for c in cols if pd.api.types.is_numeric_dtype(df[c]) and not c.startswith("ID_")]
        if num_cols:
            lines.append(f"DESCRIPTIVES VARIABLES={' '.join(num_cols[:4])}")
            lines.append("  /STATISTICS=MEAN STDDEV MIN MAX KURTOSIS SKEWNESS.")
            lines.append("")

            lines.append(f"FREQUENCIES VARIABLES={' '.join(num_cols[:3])}")
            lines.append("  /STATISTICS=STDDEV VARIANCE MEAN MEDIAN MODE SKEWNESS KURTOSIS")
            lines.append("  /ORDER=ANALYSIS.")
            lines.append("")

        cat_cols = [c for c in cols if not pd.api.types.is_numeric_dtype(df[c]) and not c.startswith("ID_")]
        if cat_cols and num_cols:
            lines.append("* 4. Template Uji Perbandingan Rata-rata & ANOVA.")
            lines.append(f"ONEWAY {num_cols[0]} BY {cat_cols[0]}")
            lines.append("  /STATISTICS DESCRIPTIVES HOMOGENEITY")
            lines.append("  /POSTHOC=TUKEY ALPHA(0.05).")
            lines.append("")

        if len(num_cols) >= 2:
            lines.append("* 5. Template Analisis Korelasi & Regresi.")
            lines.append(f"CORRELATIONS")
            lines.append(f"  /VARIABLES={num_cols[0]} {num_cols[1]}")
            lines.append("  /PRINT=TWOTAIL NOSIG")
            lines.append("  /MISSING=PAIRWISE.")
            lines.append("")
            lines.append(f"REGRESSION")
            lines.append(f"  /DEPENDENT {num_cols[1]}")
            lines.append(f"  /METHOD=ENTER {num_cols[0]}")
            lines.append("  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL.")
            lines.append("")

        return "\n".join(lines)
